
GET {{server}}/health

###
GET {{server}}/api/products

###
GET {{server}}/api/products/product/55o

###
GET {{server}}/api/products/category/001

###
POST {{server}}/api/products
Content-Type: application/json
Authorization: BEARER {{authToken}}

{
  "product_id": "sgj",
  "title": "Iphone 12",
  "description": "The latest Iphone",
  "price": "1000",
  "image": "https://www.apple.com/newsroom/images/product/iphone/standard/Apple_announce-iphone12pro_10132020_big.jpg.large.jpg",
  "owner": "XiaoLing",
  "categories": [{"category_id": "as1", "name": "Category1"}]
}

###
PUT {{server}}/api/products/d5
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "product_id": "sgj",
  "title": "Smart Watch",
  "description": "Sleek Smart Watch",
  "price": "99",
  "image": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1999&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  "owner": "XiaoLing",
  "categories": [
        {
        "category_id": "001", "name": "Electronics"
        }
    ]
}


###
DELETE {{server}}/api/products/sgj
Authorization: BEARER {{authToken}}


###
POST {{server}}/api/users/signup 
Content-Type: application/json

{
  "username": "XiaoLing",
  "email": "Xiao@Ling.com",
  "password": "Xiao"
}

### 
# @name login
POST {{server}}/api/users/login
Content-Type: application/json

{
  "email": "Xiao@Ling.com",
  "password": "Xiao"
}
### 
# @name login
POST {{server}}/api/users/login
Content-Type: application/json

{
  "email": "Xiao@Ling.com",
  "password": "Xiao"
}

###
@authToken = {{login.response.body.token}}

@server = http://localhost:5000

//@server = http://172.16.6.158:5000