
GET {{server}}/health

###
GET {{server}}/api/users/listings/622b7b30-9322-4ae8-b019-bc5db08d8d62




###
POST {{server}}/api/users/signup 
Content-Type: application/json

{
  "username": "XiaoLing",
  "email": "Xiao@Ling.com",
  "password": "Xiao"
}

### 
# @name login
POST {{server}}/api/users/login
Content-Type: application/json

{
  "email": "xiao@gmail.com",
  "password": "qwe"
}

### 
# @name login
POST {{server}}/api/users/login
Content-Type: application/json

{
  "email": "su@gmail.com",
  "password": "qwe"
}
###
@authToken = {{login.response.body.token}}

@server = http://localhost:5000

//@server = http://172.16.6.158:5000