
GET {{server}}/health

###
GET {{server}}/api/users/listings/TestUser


###
POST {{server}}/api/users/signup 
Content-Type: application/json

{
  "username": "TestUser",
  "email": "test@user.com",
  "password": "password"
}

### 
# @name login
POST {{server}}/api/users/login
Content-Type: application/json

{
  "email": "test@user.com",
  "password": "password"
}

### 
# @name login
POST {{server}}/api/users/login
Content-Type: application/json

{
  "email": "su@gmail.com",
  "password": "qwe"
}
###
@authToken = {{login.response.body.token}}

@server = http://localhost:5000

//@server = http://172.16.6.158:5000